import os



os.system("raspistill -n -sh -100 -o imagesharp0.jpg")
os.system("raspistill -n -sh -80 -o imagesharp1.jpg")
os.system("raspistill -n -sh -60 -o imagesharp2.jpg")
os.system("raspistill -n -sh -40 -o imagesharp3.jpg")
os.system("raspistill -n -sh -20 -o imagesharp4.jpg")
os.system("raspistill -n -sh -0 -o imagesharp5.jpg")
os.system("raspistill -n -sh 20 -o imagesharp6.jpg")
os.system("raspistill -n -sh 40 -o imagesharp7.jpg")
os.system("raspistill -n -sh 60 -o imagesharp8.jpg")
os.system("raspistill -n -sh 80 -o imagesharp9.jpg")



os.system("raspistill -n -co -100 -o imagecontrast0.jpg")
os.system("raspistill -n -co -80 -o imagecontrast1.jpg")
os.system("raspistill -n -co -60 -o imagecontrast2.jpg")
os.system("raspistill -n -co -40 -o imagecontrast3.jpg")
os.system("raspistill -n -co -20 -o imagecontrast4.jpg")
os.system("raspistill -n -co -0 -o imagecontrast5.jpg")
os.system("raspistill -n -co 20 -o imagecontrast6.jpg")
os.system("raspistill -n -co 40 -o imagecontrast7.jpg")
os.system("raspistill -n -co 60 -o imagecontrast8.jpg")
os.system("raspistill -n -co 80 -o imagecontrast9.jpg")



os.system("raspistill -n -br 0 -o imagebright0.jpg")
os.system("raspistill -n -br 20 -o imagebright1.jpg")
os.system("raspistill -n -br 40 -o imagebright2.jpg")
os.system("raspistill -n -br 60 -o imagebright3.jpg")
os.system("raspistill -n -br 80 -o imagebright4.jpg")


os.system("raspistill -n -sa -100 -o imagesat0.jpg")
os.system("raspistill -n -sa -80 -o imagesat1.jpg")
os.system("raspistill -n -sa -60 -o imagesat2.jpg")
os.system("raspistill -n -sa -40 -o imagesat3.jpg")
os.system("raspistill -n -sa -20 -o imagesat4.jpg")
os.system("raspistill -n -sa -0 -o imagesat5.jpg")
os.system("raspistill -n -sa 20 -o imagesat6.jpg")
os.system("raspistill -n -sa 40 -o imagesat7.jpg")
os.system("raspistill -n -sa 60 -o imagesat8.jpg")
os.system("raspistill -n -sa 80 -o imagesat9.jpg")
os.system("raspistill -n -sa 100 -o imagesat10.jpg")

os.system("raspistill -n -ISO 100 -o imageISO0.jpg")
os.system("raspistill -n -ISO 200 -o imageISO1.jpg")
os.system("raspistill -n -ISO 300 -o imageISO2.jpg")
os.system("raspistill -n -ISO 400 -o imageISO3.jpg")
os.system("raspistill -n -ISO 500 -o imageISO4.jpg")
os.system("raspistill -n -ISO 600 -o imageISO5.jpg")
os.system("raspistill -n -ISO 700 -o imageISO6.jpg")
os.system("raspistill -n -ISO 800 -o imageISO7.jpg")

os.system("raspistill -n -ex auto -o imageexposure0.jpg")
os.system("raspistill -n -ex night -o imageexposure1.jpg")
os.system("raspistill -n -ex backlight -o imageexposure2.jpg")
os.system("raspistill -n -ex spotlight -o imageexposure3.jpg")
os.system("raspistill -n -ex sports -o imageexposure4.jpg")
os.system("raspistill -n -ex snow -o imageexposure5.jpg")
os.system("raspistill -n -ex beach -o imageexposure6.jpg")
os.system("raspistill -n -ex verylong -o imageexposure7.jpg")
os.system("raspistill -n -ex fixedfps -o imageexposure8.jpg")
os.system("raspistill -n -ex antishake -o imageexposure9.jpg")
os.system("raspistill -n -ex fireworks -o imageexposure10.jpg")


os.system("raspistill -n -awb off -o off.jpg")
os.system("raspistill -n -awb auto -o auto.jpg")
os.system("raspistill -n -awb sun -o sun.jpg")
os.system("raspistill -n -awb cloud -o cloud.jpg")
os.system("raspistill -n -awb shade -o shade.jpg")
os.system("raspistill -n -awb tungsten -o tungsten.jpg")
os.system("raspistill -n -awb fluorescent -o fluorescent.jpg")
os.system("raspistill -n -awb incandescent -o incandescent.jpg")
os.system("raspistill -n -awb flash -o flash.jpg")
os.system("raspistill -n -awb horizon -o horizon.jpg")

os.system("raspistill -n -ifx none -o none.jpg")
os.system("raspistill -n -ifx negative -o negative.jpg")
os.system("raspistill -n -ifx solarise -o solarize.jpg")
os.system("raspistill -n -ifx posterise -o posterize.jpg")
os.system("raspistill -n -ifx whiteboard -o whiteboard.jpg")
os.system("raspistill -n -ifx blackboard -o blackboard.jpg")
os.system("raspistill -n -ifx sketch -o sketch.jpg")
os.system("raspistill -n -ifx denoise -o denose.jpg")
os.system("raspistill -n -ifx emboss -o emboss.jpg")
os.system("raspistill -n -ifx oilpaint -o oilpaint.jpg")
os.system("raspistill -n -ifx hatch -o hatch.jpg")
os.system("raspistill -n -ifx gpen -o gpen.jpg")
os.system("raspistill -n -ifx pastel -o pastel.jpg")
os.system("raspistill -n -ifx watercolour -o watercolour.jpg")
os.system("raspistill -n -ifx film -o film.jpg")
os.system("raspistill -n -ifx blur -o blur.jpg")
os.system("raspistill -n -ifx saturation -o saturation.jpg")
os.system("raspistill -n -ifx colourswap -o colourswap.jpg")
os.system("raspistill -n -ifx washedout -o washedout.jpg")
os.system("raspistill -n -ifx colourpoint -o colourpoint.jpg")
os.system("raspistill -n -ifx colourbalance -o colourbalance.jpg")
os.system("raspistill -n -ifx cartoon -o cartoon.jpg")

os.system("raspistill -n -mm average -o average.jpg")
os.system("raspistill -n -mm spot -o spot.jpg")
os.system("raspistill -n -mm backlit -o backlit.jpg")
os.system("raspistill -n -mm matrix -o matrix.jpg")


os.system("raspistill -n -mm average -awb incandescent -ISO 100 -ex fixedfps -sa 40 -sh 80 -o culmination.jpg")
